image: pobj

stages:
- test

TME-4:
  script: >
    /home/pobj/run.sh -id TME-4 -name TME-4
    pobj.multiset.test.HashMultiSetTest
    pobj.multiset.test.IteratorTest
    pobj.multiset.test.CollectionTest
  artifacts:
    reports:
      junit: report.xml

TME-5: 1
  script: > 2
    /home/pobj/run.sh -id TME-5 -name TME-5 3
    pobj.multiset.test.HashMultiSetTest2 4
  artifacts: 5
    reports: 6
      junit: report.xml
